version: '3.8'
services:
  php8-apache:
    container_name: php8-apache
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
    ports:
      - 8080:80
    environment:
      TZ: "Asia/Bangkok"
    networks:
      env_developer : {}
networks:
  env_developer:
    external: true
      