version: '3.9'
services:
  php8-apache:
    container_name: php8-apache
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
    ports:
      - 80:80
    environment:
      TZ: "Asia/Bangkok"
    networks:
      env_developer : {}
networks:
  env_developer:
    external: true
      