name: CI/CD DMSC
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Auto Deploy
    runs-on: 
      - dmsc-prod-server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull repository
        run: |
          rm -rf /home/website/*
          cp -r * /home/website/
          echo "Pull repository successfully..."
          rm -rf *
          echo "Clean up directory _work."

      - name: Deploy API
        run: |
          cd /wwwroot/webservice
          docker compose down
          cp -r /home/website/webservice /wwwroot
          echo "copy .env"
          cp -r /home/env/.env /wwwroot/webservice/src

      - name: Build & Start Container Image API
        run: |
          cd /wwwroot/webservice
          docker compose up --build -d
          echo "service api is running..."

      - name: Deploy front-end & back-end
        run: |
          cd /wwwroot/website
          docker compose down
          cp -r /home/website /wwwroot
          echo "copy .htaccess"
          cp -r /home/env/.htaccess /wwwroot/website
          rm -rf /wwwroot/website/webservice
          echo "copy upload & ckupload"
          rm -rf /wwwroot/website/upload/*
          cp -r /home/assets/upload/upload /wwwroot/website
          rm -rf /wwwroot/website/ckeditor/upload/*
          cp -r /home/assets/ck/upload /wwwroot/website/ckeditor
          echo "copy SSL"
          cp -r /home/_apache /wwwroot/website

      - name: Build & Start Container Image front-end & back-end
        run: |
          cd /wwwroot/website
          docker compose up --build -d
          echo "website is running..."

      - name: Clean up project temp
        run: |
          rm -rf /home/website/*
          echo "Clean up successfully..."