name: Auto Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    name: Auto Deploy
    runs-on: 
      - aws-dmsc-runner
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Start Deploy..."
          sudo rm -rf /home/website/*
          sudo cp -r * /home/website/
          sudo rm -rf *
          echo "Starting Deploy webservice..."
          sudo cp -r /home/website/webservice /wwwroot
          echo "copy .env"
          sudo cp -r /home/env/.env /wwwroot/webservice/src
          echo "Starting Docker Image webservice"
          cd /wwwroot/webservice
          docker compose down
          docker compose up --build -d
          echo "webservice is running..."

          echo "Starting Deploy website..."
          sudo cp -r /home/website /wwwroot
          sudo cp -r /home/env/.htaccess /wwwroot
          sudo rm -rf /wwwroot/website/webservice
          echo "Starting Docker Image website"
          cd /wwwroot/website
          docker compose down
          docker compose up --build -d
          echo "website is running..."

          echo "Deployment successfully..."
          sudo rm -rf /home/website/*
